[package]
name = "kaldera"
version = "0.1.0"
authors = ["Keitaro Oguri <ogukei256@gmail.com>"]
edition = "2018"

[dependencies]
libc = "*"
futures = { optional = true, version = "*", features = ["thread-pool"] }
nalgebra-glm = { optional = true, version = "*" }

[features]
default = ["use-nalgebra"]

use-nalgebra = ["nalgebra-glm"]
use-base = ["futures"]
